version: '3.8'

services:
  # Service Discovery - Eureka Server
  eureka-server:
    image: steeltoeoss/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    networks:
      - lockbox-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: lockbox-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=lockbox
      - POSTGRES_USER=lockbox
      - POSTGRES_PASSWORD=lockbox123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lockbox-network

  # PostgreSQL Exporter for Prometheus
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    ports:
      - "9187:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://lockbox:lockbox123@postgres:5432/lockbox?sslmode=disable
    depends_on:
      - postgres
    networks:
      - lockbox-network

  # Redis for Caching
  redis:
    image: redis:7-alpine
    container_name: lockbox-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lockbox-network

  # Monitoring - Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - lockbox-network

  # Monitoring - Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - lockbox-network

  # Distributed Tracing - Zipkin
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - lockbox-network

  # Log Aggregation - ELK Stack
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - lockbox-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: logstash
    volumes:
      - ./monitoring/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      - lockbox-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - lockbox-network

  # Message Queue - RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=lockbox
      - RABBITMQ_DEFAULT_PASS=lockbox123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - lockbox-network

  # LockBox Main Service
  lockbox-service:
    build: .
    container_name: lockbox-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=lockbox-service
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/lockbox
      - SPRING_DATASOURCE_USERNAME=lockbox
      - SPRING_DATASOURCE_PASSWORD=lockbox123
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
      - JAVA_OPTS=-Xmx1024m -Xms512m -XX:+UseG1GC -XX:+DisableExplicitGC
    depends_on:
      - eureka-server
      - postgres
      - redis
      - zipkin
    networks:
      - lockbox-network
    mem_limit: 1.5g
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:
  elasticsearch_data:
  rabbitmq_data:

networks:
  lockbox-network:
    driver: bridge 